In [1]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

ric = time.time()
c = np.dot(a,b)
toc = time.time()

print(str(1000*(toc-ric)) + "ms")

print(a)
print(b)

# non vectored function

c = 0
tic = time.time()
for i in range (1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print(str(1000*(toc-ric)) + "ms")

0.0ms
[0.31378083 0.20225926 0.08899196 ... 0.98387389 0.3132611  0.27526703]
[0.36827849 0.1014346  0.21077693 ... 0.61088739 0.82959239 0.02980403]
250123.52730828995
212.2819423675537ms
