# 📘 Mastering NumPy for Deep Learning (With Practice)
Welcome to this hands-on NumPy tutorial crafted for deep learning students.
By the end of this notebook, you'll be confident with NumPy operations used in ML & DL.

In [2]:
import numpy as np

## 🔹 Section 1: NumPy Basics
### Creating Arrays

In [2]:
# 1D array
arr1 = np.array([1, 2, 3])

# Zeros, ones, arange, linspace
zeros = np.zeros((2, 3))
ones = np.ones((2, 2))
range_array = np.arange(0, 10, 2)
even_spaced = np.linspace(1, 10, 5)

print("1D array:", arr1)
print("Zeros:", zeros)
print("Range:", range_array)
print("Linspace:", even_spaced)

1D array: [1 2 3]
Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Range: [0 2 4 6 8]
Linspace: [ 1.    3.25  5.5   7.75 10.  ]


### ✅ Practice:
1. Create a 1D array of even numbers between 0 and 20.
2. Create a 3x3 matrix of random integers between 1 and 10.

In [4]:
ar1 = np.arange(0,21,2)
print(ar1)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [5]:
ar1 = np.random.rand(3,3)
print(ar1)

[[0.09928909 0.99488119 0.33236226]
 [0.46185283 0.67530809 0.07569397]
 [0.36914311 0.01556948 0.1305063 ]]


## 🔹 Section 2: Shape and Reshape

In [6]:
# Reshape and flatten
arr2 = np.arange(1, 9).reshape(4, 2)
flat = arr2.flatten()
transposed = arr2.T

print("Reshaped:", arr2)
print("Flattened:", flat)
print("Transposed:", transposed)

Reshaped: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Flattened: [1 2 3 4 5 6 7 8]
Transposed: [[1 3 5 7]
 [2 4 6 8]]


### ✅ Practice:
1. Reshape a 1D array into a 4x2 matrix.
2. Flatten a 2D array and find its shape.

In [16]:
arr2 = np.arange(0, 16, 2).reshape(2,4)
print(arr2)

flat = arr2.flatten()
print("FLATTERN: ", flat)

[[ 0  2  4  6]
 [ 8 10 12 14]]
FLATTERN:  [ 0  2  4  6  8 10 12 14]


## 🔹 Section 3: Indexing, Slicing & Boolean Masking

In [ ]:
# Boolean masking
arr3 = np.array([[10, 20, 30], [5, 15, 25]])
mask = arr3 > 15 #it is use to check each element whether its greater than 15 or not
print(mask)
filtered = arr3[mask]
print("Filtered values:", filtered)

[[False  True  True]
 [False False  True]]
Filtered values: [20 30 25]


### ✅ Practice:
1. Select all elements greater than 50 in a 5x5 random matrix.
2. Replace all negative numbers in an array with 0.

In [ ]:
a = np.random.rand(5,5)*100
print(a)
mask = a > 50 
filter = a[mask]
print(filter)

[[96.02384876 94.93767253 24.8874212  91.86574064 97.98830009]
 [45.86428908 56.31733485 64.98679273  5.43347681 56.75111883]
 [55.9115055  22.11815836 58.54872911 30.37898    34.11214019]
 [45.7640323  78.8132751  65.40496593 51.69703986 49.3091002 ]
 [38.0371076  97.74658497 69.39850825 82.87019885 61.58409181]]
[96.02384876 94.93767253 91.86574064 97.98830009 56.31733485 64.98679273
 56.75111883 55.9115055  58.54872911 78.8132751  65.40496593 51.69703986
 97.74658497 69.39850825 82.87019885 61.58409181]


In [21]:
arr = np.random.randint(-100, 101, size=(3, 3))
arr[arr<0] = 0 
print(arr)

[[91 73  0]
 [36 12 89]
 [ 0 95 65]]


## 🔹 Section 4: Vectorized Operations & Broadcasting

In [3]:
# Broadcasting example
matrix = np.array([[1, 2], [3, 4]])
vector = np.array([10, 20])
result = matrix + vector
print("Broadcasted Result:", result)

Broadcasted Result: [[11 22]
 [13 24]]


### ✅ Practice:
1. Add a vector to each row of a matrix.
2. Multiply a 3x3 matrix by a scalar and compute the mean.

In [8]:
matix = np.array([[4, 20], [20, 10]])
vector = np.array([40,10])
r = matix + vector
print(r)

arr = np.random.randint(0,100, size = (3,3))
s = 10
print(arr)

[[44 30]
 [60 20]]
[[44  0 84]
 [25 79 94]
 [19 95 98]]


## 🔹 Section 5: Aggregation and Stats

In [9]:
# Aggregation
arr4 = np.random.randint(1, 100, (3, 3))
print("Array:", arr4)
print("Mean:", np.mean(arr4))
print("Std Dev:", np.std(arr4))
print("Max Index:", np.argmax(arr4))

Array: [[84 64 63]
 [71 87 16]
 [94 74 23]]
Mean: 64.0
Std Dev: 25.74231276841043
Max Index: 6


### ✅ Practice:
1. Compute mean and standard deviation of a random array.
2. Find the position of the minimum element in a matrix.

In [13]:
arr4 = np.random.randint(1, 100, (3, 3))
print(np.min(arr4))
print(arr4)
print(np.mean(arr4))
print(np.std(arr4))

8
[[ 8 65 90]
 [33 83 13]
 [66 15 67]]
48.888888888888886
29.990533485842366


## 🔹 Section 6: Linear Algebra

In [14]:
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
product = np.dot(A, B)
inv_A = np.linalg.inv(A)
norm_A = np.linalg.norm(A)

print("Dot Product:", product)
print("Inverse of A:", inv_A)
print("Norm of A:", norm_A)

Dot Product: [[19 22]
 [43 50]]
Inverse of A: [[-2.   1. ]
 [ 1.5 -0.5]]
Norm of A: 5.477225575051661


### ✅ Practice:
1. Compute the dot product of two 2D matrices.
2. Check if a matrix is invertible and find its inverse.

In [19]:
import numpy as np

A = np.array([[1, 2], [3, 4]])    # shape: (2, 2)
B = np.array([[5, 6], [7, 8]])    # shape: (2, 2)

dot = np.dot(A, B)
print("Dot product:\n", dot)

# to check whether the matrix is invertible or not its determinant should not be zero

det = np.linalg.det(dot)
print("Determinant:", det)

if det != 0:
    inverse_A = np.linalg.inv(dot)
    print("Inverse of A:\n", inverse_A)
else:
    print("Matrix is not invertible.")


Dot product:
 [[19 22]
 [43 50]]
Determinant: 4.000000000000008
Inverse of A:
 [[ 12.5   -5.5 ]
 [-10.75   4.75]]


## 🔹 Section 7: Deep Learning Prep (One-hot & Normalization)

In [20]:
# One-hot encoding
labels = np.array([0, 1, 2, 0])
one_hot = np.eye(3)[labels]
print("One-hot:", one_hot)

# Normalization
data = np.random.rand(5, 3) * 100
normalized = (data - np.mean(data)) / np.std(data)
print("Normalized:", normalized)

One-hot: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
Normalized: [[-1.1022821   1.04285185 -0.03652189]
 [ 0.49878425  1.40868705  0.66256   ]
 [-0.72271557 -1.1236462   1.57586099]
 [ 1.46136601  0.02561943 -0.7338814 ]
 [-0.94353922 -1.29312463 -0.72001857]]


### ✅ Practice:
1. Normalize a dataset of 100 samples.
2. Convert `[0, 1, 2, 0, 1]` to one-hot encoded format.

In [22]:
data = np.random.rand(100, 5) * 100  

mean = np.mean(data, axis=0)
std = np.std(data, axis=0)
normalized_data = (data - mean) / std

print("Normalized dataset shape:", normalized_data.shape)
print("First 5 normalized samples:\n", normalized_data[:5])

labels = np.array([0, 1, 2, 0, 1])
one_hot = np.eye(3)[labels] 

print("One-hot encoded output:\n", one_hot)


Normalized dataset shape: (100, 5)
First 5 normalized samples:
 [[-0.73683957 -0.55859839 -0.74812682 -0.88641744  0.29574559]
 [ 0.193725    0.83887417 -0.69136265  1.58763395  0.47331183]
 [-0.63700655  0.59130363  0.1952935   1.00529894 -0.75135883]
 [ 0.59613107 -1.49273005  0.50837909  1.32696521  0.88060391]
 [-0.50498026  0.27828197 -0.59386189  0.49751799  1.42568199]]
One-hot encoded output:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
